/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./bootstrap.min.css";

import CommonLayout from "@/component/CommonLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script src="/js/bootstrap.bundle.min.js"></script>
            </head>
            <body className={inter.className}>
                <CommonLayout>
                    {children}
                </CommonLayout>
            </body>
        </html>
    );
}
